name: Scan

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ '**' ] 
    types: [        
      opened,
      synchronize,
      reopened ]
  workflow_dispatch:
    inputs:
      Name:   
        required: true
        default: 'Re-run the workflow'
      Description:
        default: ''  


jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD }}

  Post-Notification:
    runs-on: windows-2019
    needs: scan
    # https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context
    if: ${{ github.event_name != 'schedule' && always() && (needs.scan.result == 'failure' || needs.scan.result == 'success') }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Webhook
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        run: |
          curl --write-out '%{http_code}' \
          --silent \
          -- output /dev/null \
          --request POST \
          --header 'authorization: Basic ${{ secrets.WEBHOOK_TOKEN }}' \
          --header 'content-type: application/json' \
          --url ${{ secrets.WEBHOOK_URL }} \
          --data '{ \
            "origin": "GitHub", \
            "project": "dataviz-hub", \
            "commit_title": "New release", \
            "commit_message": "${{ github.event.commits[0].message }}", \
            "commit_sha": ${{ github.sha }} \
            "outcome": "${{ needs.scan.result }}", \
            "run_url": "https://github.com/researchdata-sheffield/dataviz-hub2/actions/runs/${{ github.run_id }}", \
            "impact": "Low", \
            "benefit": "New release" \
          }' 
        